resolver: lts-14.0
packages:
- .
- /home/sino/mygithub/replica
extra-deps:
- hex-text-0.1.0.0@sha256:52dc2cf5ce45f7d86ea5e56e2ac57820f788c10bbb3fe83f6d57e678a426305b,1072
- natural-transformation-0.4
# - ./vendor/replica
# - ./vendor/concur-core
# - git: https://github.com/pkamenarsky/replica.git
#   commit: 69249ec760b8b8272d302269b54ddc4531d508a9
- git: https://github.com/pkamenarsky/concur.git
  commit: 6c6bcc07b2688182945b28f154a013eee3f624c5
  subdirs:
    - concur-core
flags: {}
extra-package-dbs: []
